### ISSUE TITLE
How to copy directories recursively?

### ISSUE THREAD

**Issue by ghost** [Fjandin/gulp-scp#5]
Following copies files in the `dist` directories but does not copy directories recursively.

```
// Scp
gulp.task('scp', function () {
  gulp.src([
    'dist/*'
  ])
  .pipe(scp({
    host: '...',
    user: '...',
    port: 22,
    path: '...'
  }));
});
```

if I use `gulp.src(['dist/**/*'])` all files are copied but the directory structure is not maintained.

**Comment by derekdata** [comment]
Did you ever figure out an acceptable workaround @dealancer ?

**Comment by ghost** [comment]
@derekdata, not really, I switched to Rsync: https://www.npmjs.com/package/gulp-rsync

**Comment by Fjandin** [comment]
Hi.

Firstly sorry for the late reply.

I would also recommend switching to rsync. I'm not actively maintaining this repo at the moment as i don't have the time for it. Also i find rsync being far superior to scp.
